export const BUCKETS = [
      {
        name: "AI มาบริหารจัดการโอกาสรับเงิน",
        color: "#8a5cd6",
        ideas: [
          [10, "ฟลุ๊ค"],
          [12, "ไก่"],
          [14, "ฟิล์ม"],
          [18, "ชัพ"],
          [19, "โอม"],
          [44, ""],
          [45, ""],
          [46, ""],
          [47, ""],
          [48, ""],
          [49, ""],
          [50, ""],
          [51, ""],
        ],
      },
      {
        name: "คุมเงินเบิก-ค่าธรรมเนียม",
        color: "#e8577a",
        ideas: [
          [6, "ดรีม"],
          [8, "หมวย"],
          [13, "จอย"],
          [22, "อั๋น"],
          [23, "เนย"],
          [25, "บี"],
          [32, "พอเพียง"],
          [34, "ซะ"],
          [38, "ส้ม"],
        ],
      },
      {
        name: "เตือน SLA / กำหนดเวลาคดี",
        color: "#f08a3c",
        ideas: [
          [5, "มิกซ์"],
          [7, "หนม"],
          [26, "ไซยานี"],
          [28, "เปรียว"],
          [30, "แพร์"],
          [33, "แนท"],
          [36, "ไอซ์"],
          [37, "อ้อม"],
          [43, "ฝ้าย"],
        ],
      },
      {
        name: "สแกน-จัดเก็บ-ตั้งชื่อไฟล์",
        color: "#3f6fd1",
        ideas: [
          [1, "รุ้ง"],
          [2, "เบียร"],
          [3, "อิ๋ว"],
          [15, "มะปราง"],
          [17, "ตั๊ก"],
          [27, "ป๋อง"],
          [35, "ผึ้ง"],
        ],
      },
      {
        name: "ตรวจความถูกต้องเอกสาร",
        color: "#1f9e96",
        ideas: [
          [4, "สินธร"],
          [11, "กุ๊ก"],
          [16, "มิ้ว"],
          [24, "มายด์"],
          [29, "ลูกแพร"],
          [31, "ตะวัน"],
          [40, "แก้ว"],
          [42, "พี"],
        ],
      },
      {
        name: "ลดกระดาษ / ต้นทุนพิมพ์",
        color: "#5aa84a",
        ideas: [
          [9, "นุช"],
          [20, "โน"],
          [21, "เนตร"],
        ],
      },
      {
        name: "ส่งงาน-รับงานระหว่างทีม",
        color: "#b07a4a",
        ideas: [
          [39, "เฟิน"],
          [41, "เบลล์"],
        ],
      },
    ];
export const NOTE_COLORS = [
      "#ffd84d",
      "#ffe98a",
      "#ffc9d6",
      "#bfe7e3",
      "#cfe0ff",
      "#ffd3a8",
    ];
export const NAMES = [
      "รุ้ง",
      "เบียร์",
      "อิ๋ว",
      "สินธร",
      "มิกซ์",
      "ดรีม",
      "ขนม",
      "หมวย",
      "นุช",
      "ไก่",
      "ฟลุ๊ค",
      "กุ๊ก",
      "จอย",
      "ฟิล์ม",
      "มะปราง",
      "มิ้ว",
      "ตั๊ก",
      "ชัพ",
      "โอม",
      "โณ",
      "เนตร",
      "อั๋น",
      "เนย",
      "มาย",
      "บี",
      "ไซ",
      "วี่",
      "ป๋อง",
      "เปรียว",
      "ลูกแพร์",
      "แพร",
      "ตะวัน",
      "พอเพียง",
      "แนท",
      "ซะ",
      "ผึ้ง",
      "ไอซ์",
      "อ้อม",
      "ส้ม",
      "เฟิร์น",
      "แก้ว",
      "เบล",
      "พี",
      "ฝ้าย",
      "บีม",
      "พี่แย้ม",
      "พี่นก",
      "พี่แอน",
      "พี่แหม่ม",
      "พี่แอ๋ว",
      "พี่อ้า",
      "พี่จิ๊บ",
    ];
export const DOODLES = {
      pa: [["s-sparkle", "top:2cqi;right:4cqi;width:7cqi", 0]],
      pb: [["s-star", "top:2cqi;right:4cqi;width:7cqi", 10]],
      t: [
        ["s-star", "top:3cqi;left:5cqi;width:8cqi", -12],
        ["s-sparkle", "top:4cqi;right:6cqi;width:7cqi", 0],
        ["s-flower", "bottom:4cqi;left:4cqi;width:8cqi", 0],
        ["s-star", "bottom:5cqi;right:5cqi;width:7cqi", 14],
      ],
      p1: [
        ["s-sparkle", "top:2cqi;right:4cqi;width:7cqi", 0],
        ["s-flower", "top:30%;right:3cqi;width:8cqi", 10],
        ["s-heart", "top:44%;left:2cqi;width:6cqi", -12],
      ],
      p2: [
        ["s-rainbow", "top:2cqi;right:4cqi;width:13cqi", 0],
        ["s-sparkle", "top:66%;left:6cqi;width:7cqi", 0],
        ["s-sparkle", "top:62%;right:8cqi;width:5cqi", 0],
        ["s-star", "bottom:4cqi;left:40%;width:6cqi", 12],
      ],
      p3: [
        ["s-star", "top:2cqi;right:4cqi;width:7cqi", 14],
        ["s-heart", "bottom:3cqi;left:9cqi;width:5cqi", -8],
      ],
      p4: [
        ["s-sparkle", "bottom:4cqi;right:10cqi;width:7cqi", 0],
        ["s-flower", "bottom:3cqi;left:40%;width:7cqi", 0],
      ],
      p5: [["s-sparkle", "top:2cqi;right:4cqi;width:7cqi", 0]],
      p6: [["s-star", "top:2cqi;right:4cqi;width:7cqi", -8]],
      p7: [
        ["s-sparkle", "top:2cqi;right:4cqi;width:7cqi", 0],
        ["s-heart", "top:22%;right:3cqi;width:5cqi", 10],
      ],
      p8: [
        ["s-sparkle", "top:2cqi;right:4cqi;width:7cqi", 0],
        ["s-heart", "bottom:3cqi;left:40%;width:5cqi", 10],
      ],
      p9: [
        ["s-star", "top:2cqi;right:4cqi;width:7cqi", 12],
        ["s-bulb", "bottom:5cqi;right:8cqi;width:10cqi", -8],
        ["s-sparkle", "bottom:6cqi;left:44%;width:6cqi", 0],
        ["s-flower", "bottom:4cqi;left:10cqi;width:7cqi", 0],
      ],
      p10: [
        ["s-sparkle", "top:2cqi;right:4cqi;width:7cqi", 0],
        ["s-star", "top:30%;right:6cqi;width:8cqi", 14],
        ["s-heart", "top:46%;right:14cqi;width:5cqi", -10],
      ],
    };
export const TILE_COLORS = [
      "#f4a7b9",
      "#f6efdf",
      "#4f78c4",
      "#f6efdf",
      "#e8683a",
      "#5fae93",
      "#f2b632",
      "#f4a7b9",
    ];
